import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "./utils";

/**
 * Style variants for the {@link Badge} component.
 *
 * Generated by `class-variance-authority`. The available visual variants are:
 * - `default`
 * - `secondary`
 * - `destructive`
 * - `outline`
 */
const badgeVariants = cva(
  "inline-flex items-center justify-center rounded-md border px-2 py-0.5 text-xs font-medium w-fit whitespace-nowrap shrink-0 [&>svg]:size-3 gap-1 [&>svg]:pointer-events-none focus-visible:border-ring focus-visible:ring-ring/50 focus-visible:ring-[3px] aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive transition-[color,box-shadow] overflow-hidden",
  {
    variants: {
      variant: {
        default:
          "border-transparent bg-primary text-primary-foreground [a&]:hover:bg-primary/90",
        secondary:
          "border-transparent bg-secondary text-secondary-foreground [a&]:hover:bg-secondary/90",
        destructive:
          "border-transparent bg-destructive text-white [a&]:hover:bg-destructive/90 focus-visible:ring-destructive/20 dark:focus-visible:ring-destructive/40 dark:bg-destructive/60",
        outline:
          "text-foreground [a&]:hover:bg-accent [a&]:hover:text-accent-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  },
);

/**
 * Props for the {@link Badge} component.
 *
 * Extends the native `<span>` element props and adds the `variant` visual style
 * option as well as the optional `asChild` composition helper.
 */
type BadgeProps = React.ComponentProps<"span"> &
  VariantProps<typeof badgeVariants> & {
    /**
     * When `true`, the badge will clone its single child element and merge the
     * badge props into it instead of rendering a `<span>`.
     */
    asChild?: boolean;
  };

/**
 * A small status indicator badge.
 *
 * Renders a rounded, inline label and supports a set of visual variants. Use the
 * `asChild` prop to compose the badge styles onto a child element such as a link
 * or button.
 *
 * @example
 * ```tsx
 * <Badge>New</Badge>
 * <Badge variant="destructive">Error</Badge>
 * <Badge asChild>
 *   <a href="/labels/new">New label</a>
 * </Badge>
 * ```
 */
function Badge({
  className,
  variant = "default",
  asChild = false,
  ...props
}: BadgeProps) {
  // Only use `Slot` when `asChild` is explicitly `true` so that accidental
  // truthy non-boolean values do not enable slotted composition mode.
  const Comp = asChild === true ? Slot : "span";

  return (
    <Comp
      data-slot="badge"
      className={cn(badgeVariants({ variant }), className)}
      {...props}
    />
  );
}

export { Badge, badgeVariants };